name: Docker Image CI

on:
  repository_dispatch:
    types: [build_completed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v3
        with:
          name: demo-0.0.1-SNAPSHOT.jar
          path: ./build/libs



   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
