name: Docker

on:
  workflow_run:
    workflows: ["Gradle"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore jar from cache
        uses: actions/cache@v2
        with:
          path: build/libs
          key: jar-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/settings.gradle', '**/gradle.properties') }}

      - name: Login to Github
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current date
        run: echo "CURRENT_DATE=$(date +'%d%m%Y')" >> $GITHUB_ENV

      - name: Build the Docker image
        run: docker build . -t scoya/testimage:${{ env.CURRENT_DATE }}

      - name: Push Docker image
        run: docker push scoya/testimage:${{ env.CURRENT_DATE }}

