name: Docker

on:
  workflow_run:
    workflows: ["Gradle"]
    types:
      - completed

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Restore jar from cache
        uses: actions/cache@v2
        with:
          path: build/libs
          key: jar-${{ runner.os }}-${{ hashFiles('**/build.gradle', '**/settings.gradle', '**/gradle.properties') }}


      - name: Build the Docker image
        run: docker build . --t my-image:latest
