name: Docker Image CI

on:
  repository_dispatch:
    types: [build_completed]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download artifact from Release
      uses: actions/download-release-asset@v1
      with:
        repository: AlexanderHalfen/actions-test
        token: ${{ secrets.rep_token }}
        release_id: ${{ github.event.release.id }}
        asset_name: demo-0.0.1-SNAPSHOT.jar
        download_path: ./build/libs


   # - name: Build the Docker image
    #  run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
